### ISSUE TITLE
Suggestion: normalize names of files

### ISSUE THREAD

**Issue by neubig** [masakhane-io/masakhane-ner#15]
Right now the names of some files/directories are full language names (e.g. https://github.com/masakhane-io/masakhane-ner/tree/main/ner_data) and some are three-letter language codes (e.g. https://github.com/masakhane-io/masakhane-ner/tree/main/entity_analysis/XLM-R). Maybe they could be standardized to consistently use one or the other? I prefer language codes personally, but either would be fine.

**Comment by dadelani** [comment]
Thank you for the suggestion. Just renamed the language datasets with their three-letter language codes.

**Comment by neubig** [comment]
Thanks, that's helpful, but it's still not fixed in all of the entity_analysis directories (biLSTMCRF for example).

**Comment by dadelani** [comment]
I have fixed the issue for biLSTM and binaryGAZ. Thank you.

**Comment by neubig** [comment]
Thanks, looks like things are consistent!
