### ISSUE TITLE
Improve readme.md

### ISSUE THREAD

**Issue by hugolpz** [masakhane-io/masakhane-ner#17]
Definition : What this code does ?
Install: Required dependencies, commands to install ?
Run: demo run command.
Contribute: how to add a language ?
License.

Thank a lot for this project. 🙏🏼 African languages need more of those.

**Comment by dadelani** [comment]
thank you for the suggestion, we will work on it.

**Comment by hugolpz** [comment]
I have ton of experience is Readme.md writing, i can help a bit for the form. So its as concise, standard, and clean as possible. How should i proceed: PR or becoming a temporary member ? PR you can review before accepting my edits

**Comment by dadelani** [comment]
Thank you for the offer, you can send a pull request, and we can review. If you want to join in the project, please join Masakhane slack https://www.masakhane.io/

**Comment by hugolpz** [comment]
Thank ; )
I got too many open liguistic projects already so i plan to do tiny sprints on the readme. PR will suit well 👍🏼

**Comment by hugolpz** [comment]
It the project expected to continue and expand or is this a final work, here to be archived ?

**Comment by dadelani** [comment]
the project is expected to expand

**Comment by hugolpz** [comment]
PR #20 and #14 are ready to be merged in. I encourage you to do it in this order.

**Comment by hugolpz** [comment]
Thanks for merging in #20. Please remember #14 as well.
