### ISSUE TITLE
Repository license 

### ISSUE THREAD

**Issue by hugolpz** [masakhane-io/masakhane-ner#21]
The [arxiv](https://arxiv.org/abs/2103.11811) document states the research as under open license CC-BY.

Can the authors confirm this code is open source, open license ?

I can then submit a PR with GNU + CC-BY license.

**Comment by dadelani** [comment]
The code is open source but the data can only be used for non-commercial purpose. So, it is CC-BY-NC 4.0

**Comment by keleog** [comment]
https://github.com/masakhane-io/masakhane-ner/commit/2e5da6bd0e1c93f0f482c244f0df0dbf7fa0be7c
