### ISSUE TITLE
Poorly formatted line(s?) in masakhaner datasets

### ISSUE THREAD

**Issue by neubig** [masakhane-io/masakhane-ner#22]
Hello!

It seems that there is at least one poorly formatted line in the [masakhaner-sna train split](https://github.com/masakhane-io/masakhane-ner/blob/main/MasakhaNER2.0/data/sna/train.txt) (the middle one below): 

```
...
Hospital I-ORG
1487 Doctors'I-ORG
Association I-ORG
...
```

And one in the [swa dataset](https://github.com/masakhane-io/masakhane-ner/blob/main/MasakhaNER2.0/data/swa/train.txt):

```
. O
248 '
248 "
```

@dadelani seems like this should be fixed?

**Comment by dadelani** [comment]
Hello,
Thank you for pointing the issues. They have been fixed.

**Comment by neubig** [comment]
Thanks a bunch!
